version: '3.8'

services:
  api_server:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn api:app --host 0.0.0.0 --port 8000
    volumes:
      - ./:/app
    ports:
      - "7419:8000"
    depends_on:
      - redis
    restart: always
    env_file:
      .env

  balance_watcher:
    build:
      context: .
      dockerfile: Dockerfile
    command: python main.py
    volumes:
      - ./:/app
    depends_on:
      - redis
    restart: always
    env_file:
      .env

  redis:
    image: "redis:alpine"
    expose:
      - "6379"
    restart: always
